# Generated by Django 4.2.30 on 2026-07-03 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AIConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('source', models.CharField(choices=[('parent_qa', 'Parent Q&A'), ('student_doubt', 'Student Doubt Solving'), ('auto_summary', 'Auto Progress Summary')], max_length=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('tokens_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('sender_type', models.CharField(choices=[('teacher', 'Teacher'), ('parent', 'Parent'), ('admin', 'Admin')], max_length=10)),
                ('target_scope', models.CharField(blank=True, choices=[('all_parents', 'All Parents'), ('specific_batch', 'Specific Batch'), ('specific_class', 'Specific Class'), ('single_parent', 'Single Parent')], help_text='Used for teacher/admin notices', max_length=20)),
                ('target_class', models.CharField(blank=True, help_text='When target_scope is specific_class', max_length=20)),
                ('notice_type', models.CharField(choices=[('class_off', 'Class Off'), ('announcement', 'Announcement'), ('leave_request', 'Leave Request'), ('query', 'Query'), ('general_note', 'General Note'), ('fee_reminder', 'Fee Reminder')], default='general_note', max_length=15)),
                ('status', models.CharField(choices=[('sent', 'Sent'), ('seen', 'Seen'), ('acknowledged', 'Acknowledged')], default='sent', max_length=15)),
                ('teacher_reply', models.TextField(blank=True, help_text="Teacher's reply to parent note")),
                ('reply_date', models.DateTimeField(blank=True, null=True)),
                ('expiry_date', models.DateField(blank=True, help_text='Auto-hide after this date', null=True)),
                ('is_pinned', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-date_posted'],
            },
        ),
    ]
