# Generated by Django 4.2.30 on 2026-07-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('communications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_notices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='notice',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Required for parent-originated notices', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='core.student'),
        ),
        migrations.AddField(
            model_name='notice',
            name='target_batch',
            field=models.ForeignKey(blank=True, help_text='When target_scope is specific_batch', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notices', to='core.batch'),
        ),
        migrations.AddField(
            model_name='aiconversationlog',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to='core.student'),
        ),
        migrations.AddField(
            model_name='aiconversationlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_conversations', to=settings.AUTH_USER_MODEL),
        ),
    ]
