# Generated by Django 4.2.30 on 2026-07-03 13:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testscore',
            name='concept',
            field=models.ForeignKey(blank=True, help_text='Optional: specific chapter/concept tested', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='test_scores', to='core.concept'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='entered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_scores', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='testscore',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='core.student'),
        ),
        migrations.AddField(
            model_name='testscore',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_scores', to='core.subject'),
        ),
        migrations.AddField(
            model_name='homework',
            name='assigned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_homework', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='homework',
            name='batch',
            field=models.ForeignKey(blank=True, help_text='Assign to entire batch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='core.batch'),
        ),
        migrations.AddField(
            model_name='homework',
            name='student',
            field=models.ForeignKey(blank=True, help_text='Leave blank if assigned to entire batch', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='core.student'),
        ),
        migrations.AddField(
            model_name='homework',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='core.subject'),
        ),
        migrations.AddField(
            model_name='feerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_records', to='core.student'),
        ),
        migrations.AddField(
            model_name='conceptmastery',
            name='concept',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_mastery', to='core.concept'),
        ),
        migrations.AddField(
            model_name='conceptmastery',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='concept_mastery', to='core.student'),
        ),
        migrations.AddField(
            model_name='conceptmastery',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_mastery', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='marked_by',
            field=models.ForeignKey(limit_choices_to={'role__in': ['teacher', 'admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendance', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='core.student'),
        ),
        migrations.AlterUniqueTogether(
            name='feerecord',
            unique_together={('student', 'month')},
        ),
        migrations.AlterUniqueTogether(
            name='conceptmastery',
            unique_together={('student', 'concept')},
        ),
        migrations.AlterUniqueTogether(
            name='attendance',
            unique_together={('student', 'date')},
        ),
    ]
